name: Manually triggered workflow
on:
  workflow_dispatch:
   
jobs:
  prod-deploy:
    name: Deploy prod-deploy
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - name: deployprod-step 1
      run: echo " Manual event triggered!"