name: Automatic triggered workflow
on:
  workflow_dispatch:
    inputs:
      job:
        description: 'Job to run.'
        required: true
        default: 'prod-deploy'
      environment:
        description: 'Environment to run'     
        required: true
        default: 'only_deploy'
  push:
    branches:
      - main
  
jobs:
  dev-deploy:
    name: Deploy dev-deploy
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - name: deploydev - step 1
      if: github.event.inputs.environment != 'only_deploy'
      run: echo "Automatic event triggered!"

  stg-deploy:
    name: Deploy stg-deploy
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - name: deploystg-step 1
      if: github.event.inputs.environment != 'only_deploy'
      run: echo "Automatic event triggered!"

  prod-deploy:
    name: Deploy prod-deploy
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Running prod env
        if: (github.event.inputs.environment == 'only_deploy' ||  github.event.inputs.environment == 'all')
        run: echo "Running prod env with mode ${{ github.event.inputs.mode }}"