name: Manually triggered workflow
on:
  push:
    branches:
      - main
  
jobs:
  dev-deploy:
    name: Deploy dev-deploy
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - name: deploydev - step 1
      run: echo "Automatic event triggered!"

  stg-deploy:
    name: Deploy stg-deploy
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - name: deploystg-step 1
      run: echo "Automatic event triggered!"