name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      job:
        description: 'Job to run.'
        required: true
        default: 'prod-deploy'
  push:
    inputs:
      job:
        description: 'Job to run.'
        required: true
        default: 'dev-deploy'
    branches:
      - main
  
jobs:
  dev-deploy:
    name: Deploy dev-deploy
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - name: deploydev - step 1
      run: echo "Automatic event triggered!"

  prod-deploy:
    name: Deploy prod-deploy
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - name: deployprod-step 1
      run: echo " Manual event triggered!"