name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run'     
        required: true
        default: 'development'
      mode:
        description: 'Running mode'  
   
jobs:
  prod-deploy:
    name: Deploy prod-deploy
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Running dev env
        if: github.event.inputs.environment == 'development'
        run: echo "Running dev env with mode ${{ github.event.inputs.mode }}"
      - name: Running prod env
        if: github.event.inputs.environment == 'production'
        run: echo "Running prod env with mode ${{ github.event.inputs.mode }}"