name: Manual triggered workflow
on:
  workflow_dispatch:
    inputs:
      job:
        description: 'job to run'     
        required: true
        default: 'deploy_dev'
  push:
    branches:
      - main
  
jobs:
  lintern:
    name: Lintern
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name != 'workflow_dispatch'
    steps:
    - name: pushimage - step 1
      run: echo "Automatic lintern event triggered!"

  test:
    name: Tests
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name != 'workflow_dispatch'
    steps:
    - name: pushimage - step 1
      run: echo "Automatic test event triggered!"


  push_image:
    needs: [ lintern , test ]
    if: |  
      always() &&
      (needs.test.result == 'skipped' || needs.test.result == 'success' ) &&
      (needs.lintern.result == 'skipped' || needs.lintern.result == 'success' ) &&
      github.ref == 'refs/heads/main'
    name: Push image
    runs-on: ubuntu-latest
    steps:
    - name: pushimage - step 1
      run: echo "Push image event triggered!"

  deploy_dev:
    needs: [ push_image ]
    name: Deploy deploy_dev
    runs-on: ubuntu-latest
    if: |
      always() &&
      (needs.push_image.result == 'success') &&
      github.ref == 'refs/heads/main' &&
      (github.event.inputs.job == 'deploy_dev' ||  github.event_name != 'workflow_dispatch' )
    steps:
    - name: deploydev - step 1
      run: echo "Deploy dev triggered!"

  deploy_stg:
    needs: [ push_image ]
    name: Deploy deploy_stg
    runs-on: ubuntu-latest
    if: | 
      always() &&
      (needs.push_image.result == 'success') &&
      github.ref == 'refs/heads/main' &&
      (github.event.inputs.job == 'deploy_stg' ||  github.event_name != 'workflow_dispatch' )
    steps:
    - name: deploystg-step 1
      run: echo "Deploy staging triggered!"

  deploy_test:
    needs: [ push_image ]
    name: Deploy deploy_test
    runs-on: ubuntu-latest
    if: |
      always() &&
      (needs.push_image.result == 'success') &&
      github.ref == 'refs/heads/main' &&
      (github.event.inputs.job == 'deploy_test' ||  github.event_name != 'workflow_dispatch' )
    steps:
      - name: Running prod env
        run: echo "Deploy test triggered"
