name: CI

on:
  push:
  #pull_request:
    branches:
      #- main
      - toghr

jobs:
  push_image:
    name: 'Build & Push Image'
    #if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/staging' || github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: 'Test'
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
      
      - name: 'List changed files'
        id: 'files'
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'json'
      - run: |
          for changed_file in ${{ steps.files.outputs.added_modified }}; do
          echo "Do something with this ${changed_file}."
          done
      #- uses: actions/checkout@v2
      #- run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u $GITHUB_ACTOR --password-stdin
      #- run: echo 
      #- run: docker pull docker.pkg.github.com/$GITHUB_REPOSITORY/build-cache-no-buildkit || true
      #- run: docker build . -t thing --cache-from=docker.pkg.github.com/$GITHUB_REPOSITORY/build-cache-no-buildkit
      #- run: docker tag thing docker.pkg.github.com/$GITHUB_REPOSITORY/build-cache-no-buildkit && docker push docker.pkg.github.com/$GITHUB_REPOSITORY/build-cache-no-buildkit || true
